spring.application.name=super-mario-bros-3

# Database provider: NITRITE or MONGO_DB
db.provider=MONGO_DB

# Nitrite ##############################################################################################################
db.nitrite.file-path=./smb3.db
db.nitrite.compress=false

# MongoDB ##############################################################################################################
spring.data.mongodb.host=
spring.data.mongodb.port=27017
spring.data.mongodb.database=
spring.data.mongodb.collection.tiles=tiles
spring.data.mongodb.collection.level-scenes=levelScenes
spring.data.mongodb.collection.configuration=configuration
spring.data.mongodb.username=
spring.data.mongodb.password=

#logging.level.house.x1337.app.smb3.game.player.level.LevelScenePlayer=DEBUG
