package house.x1337.app.smb3.model.game.player.level.dimension;

import static house.x1337.app.smb3.GameConstants.PIXELS_TO_GAME_UNITS;
import static house.x1337.app.smb3.GameConstants.TILE_SPRITE_SIZE;

public interface RaccoonDimensions {
    float SPRITE_WIDTH_PIXELS = TILE_SPRITE_SIZE * 2.0f - TILE_SPRITE_SIZE / 2.0f;
    float SPRITE_HEIGHT_PIXELS = TILE_SPRITE_SIZE * 2.0f;
    float SKID_SPRITE_WIDTH_PIXELS = TILE_SPRITE_SIZE;

    float BODY_WIDTH_PIXELS = TILE_SPRITE_SIZE;
    float DUCK_SPRITE_WIDTH_PX = SPRITE_WIDTH_PIXELS - 1;
    float DUCK_QUAD_WIDTH = DUCK_SPRITE_WIDTH_PX * PIXELS_TO_GAME_UNITS;
    float QUAD_HEIGHT = SPRITE_HEIGHT_PIXELS * PIXELS_TO_GAME_UNITS;
    float QUAD_WIDTH = SPRITE_WIDTH_PIXELS * PIXELS_TO_GAME_UNITS;
    float SKID_QUAD_WIDTH = SKID_SPRITE_WIDTH_PIXELS * PIXELS_TO_GAME_UNITS;
    float TAIL_OVERFLOW_PIXELS = SPRITE_WIDTH_PIXELS - BODY_WIDTH_PIXELS;
    float TAIL_OFFSET = TAIL_OVERFLOW_PIXELS * PIXELS_TO_GAME_UNITS;
}
